[
	{
		"type": "db.kind",
		"object": "org.webosinternals.pulseaudio.settings:1",
		"caller": "org.webosinternals.pulseaudio.settings",
		"operations": {
			"create": "allow",
			"read": "allow",
			"update": "allow",
			"delete": "allow"
		}
	},
	{
		"type": "db.kind",
		"object": "org.webosinternals.pulseaudio.settings:1",
		"caller": "org.webosinternals.pulseaudio.settings.srv",
		"operations": {
			"create": "allow",
			"read": "allow",
			"update": "allow",
			"delete": "allow"
		}
	}
]
